<?php


require_once dirname(__FILE__).'/../../../../includes/classes/VehicleTypeFilter.php';
require_once dirname(__FILE__).'/../../../../includes/classes/BrandFilter.php';
require_once dirname(__FILE__).'/../../../../includes/classes/NullFilter.php';

function vehicle_maintenance_table_perm() {
    return array('view_vehicles_search');
}



function vehicle_maintenance_table_block($op='list', $delta=0, $edit=array())
{
    require dirname(__FILE__).'/../../../../includes/paths.php';
      $block = array();
    if($op == 'list')
    {
        $block[0]["info"] = t('Vehicles Maintenance Table Block');
    }
 elseif($op == 'view') {
     $brand = isset($_GET['marca']) ? urldecode($_GET['marca']) : 'nissan';
     
     
     $query = "SELECT * FROM {node} WHERE type = 'vehicle'";
     $results = db_query($query);
     
     $vehicleNodes = array();
     while($result = db_fetch_object($results))
     {
         
         $vehicleNode = node_load($result->nid);
         
         if($vehicleNode->field_vehicle_brand[0]['value'] == $brand)
            $vehicleNodes []= $vehicleNode;
     }
     
     
     $recivedUrlModel = urldecode($_GET['modelo']);
     
     $block['subject'] = 'Vehicle Search Result';
     $block['content'] = '';
     
     $block['content'] .= '<h2>';
        $block['content'] .= 'Tarifas de Mantenimiento';        
     $block['content'] .= '</h2>';
     
     $block['content'] .= '<p>';
        $block['content'] .='Con la intención de que el cliente prepare su presupuesto antes de visitarnos, presentamos las Tarifas de Mantenimientos para los diferentes modelos y sus respectivos kilometrajes/tiempos.  Estos precios incluyen las diferentes inspecciones recomendadas por el fabricante, repuestos originales, técnicos capacitados para nuestras marcas, acceso a información técnica actualizada y la utilización de los equipos y herramientas avanzadas sugeridas por los fabricantes.';
     $block['content'] .= '</p>';
             
             
             
     $block['content'] .= '<h2 id="maintenanace-header">';
        $block['content'] .= 'Programa de Mantenimiento para Vehículos '.$brand;
     $block['content'] .= '</h2>';
     
     $block['content'] .= '<p>';
        $block['content'] .= 'Repuestos Originales * Técnicos de '.ucfirst($brand).' capacitados * Información Técnica Actualizada * Equipos y Herramientas Avanzados';
     $block['content'] .= '</p>';
     $block['content'] .= '<table class="maintenance-prices">';
     
     $block['content'] .= '<tr>';     
            
               $block['content'] .= '<th class="vertical-td" rowspan="'.(count($vehicleNodes)+1).'">';                             
                    $block['content'] .= '<span id="maintenance-model-title"></span>';                                    
                $block['content'] .= '</th>'; 
            
            $block['content'] .= '<th class="category-header">';
                $block['content'] .= "Intervalos(1,000 KM)";
            $block['content'] .= '</th>';  
     
            $block['content'] .= '<th>';
                $block['content'] .= "Cada 5,000 Km";
            $block['content'] .= '</th>';  
            
            $block['content'] .= '<th>';
                $block['content'] .= "10/30/50/70/90";
            $block['content'] .= '</th>';  
            
            $block['content'] .= '<th>';
                $block['content'] .= "20/60/140";
            $block['content'] .= '</th>';  
            
            $block['content'] .= '<th>';
                $block['content'] .= "40/80/120/160";
            $block['content'] .= '</th>';  
            
            $block['content'] .= '<th>';
                $block['content'] .= "100,000 km";
            $block['content'] .= '</th>';  
            
     $block['content'] .= '</tr>';            
               
     $i = 0;
     
     foreach ($vehicleNodes as $rowNode)
     {
         
        $selcetedClass = strtolower($rowNode->field_vehicle_model[0]['value']) == $recivedUrlModel? ' maintenance-table-selected-vehicle' : '';
        $block['content'] .= '<tr class="maintenance-table-vehicle-info'.$selcetedClass.'">';     
              $block['content'] .= '<td class="model-name first-column">';                                             
                $block['content'] .= $rowNode->field_vehicle_model[0]['value'];
                $block['content'] .= '</td>'; 
                      
            
            $block['content'] .= '<td class="maintenance-table-vehicle-price">';
                $block['content'] .= $rowNode->field_maintenance_price_3_month[0]['value'];
            $block['content'] .= '</td>';
            
            $block['content'] .= '<td class="maintenance-table-vehicle-price">';
                $block['content'] .= $rowNode->field_maintenance_price_6_month[0]['value'];
            $block['content'] .= '</td>';
            
            $block['content'] .= '<td class="maintenance-table-vehicle-price">';
                $block['content'] .= $rowNode->field_maintenance_price_12_month[0]['value'];
            $block['content'] .= '</td>';
            
            $block['content'] .= '<td class="maintenance-table-vehicle-price">';
                $block['content'] .= $rowNode->field_maintenance_price_24_month[0]['value'];
            $block['content'] .= '</td>';
            
            $block['content'] .= '<td class="maintenance-table-vehicle-price">';
                $block['content'] .= $rowNode->field_maintenance_price_60_month[0]['value'];
            $block['content'] .= '</td>';
        $block['content'] .= '</tr>';     
     }
     
     $block['content'] .= '  <tr>
      
        <td id="contenido-del-mantenimiento" class="vertical-td category-header" colspan="7">Contenido del mantenimiento</td>
        
    
    </tr>
    
    <tr>
        <td id="cambio-vertical" class="vertical-td " rowspan="14"> <span id="cambio-vertical-text"></span></td>
        <td class="first-column maintenance-table-contenido-mantenimiento-cell">Aceite de motor</td>
        <td class="maintenance-table-contenido-mantenimiento-cell"  class="maintenance-table-contenido-mantenimiento-cell">x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
    </tr>
    
    
    <tr>        
        <td class="first-column maintenance-table-contenido-mantenimiento-cell">Filtro de Aceite de Motor</td>    
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
    </tr>
    
    
    <tr>        
        <td class="first-column maintenance-table-contenido-mantenimiento-cell">Filtro de Combustible</td>    
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
    </tr>
    
    
    <tr>        
        <td class="first-column maintenance-table-contenido-mantenimiento-cell">Filtro de Aire de Motor</td>    
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
    </tr>
    
    <tr>        
        <td class="first-column maintenance-table-contenido-mantenimiento-cell">Filtro de A/C y/o Fitlro Anti-Polen</td>    
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
    </tr>
    
    <tr>        
        <td  class="first-column maintenance-table-contenido-mantenimiento-cell">
            Bujías <br/>
            40/80/120/160: Convencional<br/>
            100: Punta de Platino o Iridio
        </td>    
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
    </tr>
    
    <tr>        
        <td class="first-column maintenance-table-contenido-mantenimiento-cell">Refigerante de Motor </td>    
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
    </tr>
    
    <tr>        
        <td class="first-column maintenance-table-contenido-mantenimiento-cell">L&iacute;quido de Frenos</td>    
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
    </tr>
    
    <tr>        
        <td class="first-column maintenance-table-contenido-mantenimiento-cell">
            Aceite de la Transmisi&oacute;<br/>
            40/80/100/120/160: Manual<br/>
            80/120/160: Autom&aacute;
        </td>    
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
    </tr>
    
    
    <tr>        
        <td class="first-column maintenance-table-contenido-mantenimiento-cell">
           Aceite de la Transferencia 
        </td>    
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
    </tr>
    
    <tr>
          
        <td class="first-column maintenance-table-contenido-mantenimiento-cell">
         Aceite del Diferencial
        </td>    
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" ></td>
    </tr>
    
    <tr>        
        <td class="first-column maintenance-table-contenido-mantenimiento-cell">
         Frenos (Bandas, Discos, Tambores)
        </td>    
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
    </tr>
    
    
    <tr>        
        <td  class="first-column maintenance-table-contenido-mantenimiento-cell">
         Luces y Señales
        </td>    
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
    </tr>
    
    <tr>        
        <td class="first-column maintenance-table-contenido-mantenimiento-cell">
         Agua Limpiavidrios
        </td>    
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
    </tr>
    
    <tr>      
    
         <td class="vertical-td" rowspan="14"> <span id="inspeccion-vertical"></span></td>
        <td class="first-column maintenance-table-contenido-mantenimiento-cell">
         Cerraduras, Bisagras y Cerrojo Baul
        </td>    
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
    </tr>
    
    <tr>        
        <td class="first-column maintenance-table-contenido-mantenimiento-cell">
         Sistema de Escape
        </td>    
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
    </tr>
    
    
    <tr>        
        <td class="first-column maintenance-table-contenido-mantenimiento-cell">
         Ejes Delanteros y Traseros
        </td>    
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
    </tr>
    
    
    <tr>        
        <td class="first-column maintenance-table-contenido-mantenimiento-cell">
            Correas, Mangueras y Tuber&iacute;as
        </td>    
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
    </tr>
    
    
    <tr>        
        <td class="first-column maintenance-table-contenido-mantenimiento-cell">
            Apretar Soporte de Carrocer&iacute;a
        </td>    
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
    </tr>
    
    
    <tr>        
        <td class="first-column maintenance-table-contenido-mantenimiento-cell">
            Alineaci&oacute;n y Presi&oacute;n de Aire Gomas
        </td>    
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
    </tr>
    
    
    <tr>        
        <td class="first-column maintenance-table-contenido-mantenimiento-cell">
            Rotaci&oacute;n de Gomas
        </td>    
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
        <td class="maintenance-table-contenido-mantenimiento-cell" >x</td>
    </tr>';
     
     
     $block['content'] .= '<tr id="maintenance-table-last-row">';
        $block['content'] .= '<td class="first-column">';
        $block['content'] .= 'Tiempo de trabajo (Horas)';
        $block['content'] .= '</td>';
        
        $block['content'] .= '<td>';
        $block['content'] .= '0.5';
        $block['content'] .= '</td>';
        
        $block['content'] .= '<td>';
        $block['content'] .= '1';
        $block['content'] .= '</td>';
        
        $block['content'] .= '<td>';
        $block['content'] .= '1.5';
        $block['content'] .= '</td>';
        
        $block['content'] .= '<td>';
        $block['content'] .= '3.5';
        $block['content'] .= '</td>';
        
        $block['content'] .= '<td>';
        $block['content'] .= '1.5';
        $block['content'] .= '</td>';
        
        
     $block['content'] .= '</tr>';
     $block['content'] .= '</table>';
     
     $block['content'] .= '<p id="maintenance-bottom-banner">';
        $block['content'] .= 'Precios Incluyen Itbis <br/>';
        $block['content'] .= 'Precios Están Sujetos a Variación sin Previo Aviso<br/>';
        $block['content'] .= 'No Todos los Modelos Están Incluidos';
        
     $block['content'] .= '</p>';
     
     
 }
 
 return $block;
    
}


 