<?php

require_once dirname(__FILE__) . '/../../../../includes/classes/VehicleTypeFilter.php';
require_once dirname(__FILE__) . '/../../../../includes/classes/BrandFilter.php';
require_once dirname(__FILE__) . '/../../../../includes/classes/NullFilter.php';

function maintenance_finder_perm() {
    return array('view_vehicles_search');
}

function maintenance_finder_block($op='list', $delta=0, $edit=array()) {
    require dirname(__FILE__) . '/../../../../includes/paths.php';
    $block = array();
    if ($op == 'list') {
        $block[0]["info"] = t('Front Page Maintenance Finder Block');
    } elseif ($op == 'view') {



        $query = "SELECT * FROM {node} WHERE type = 'vehicle'";
        $results = db_query($query);
        $brandsAndModels = array();
        $rowNodes = array();

        while ($result = db_fetch_object($results)) {

            $resultNode = node_load($result->nid);

            if (isset($brandsAndModels[$resultNode->field_vehicle_brand[0]['value']])) {
                $brandsAndModels[$resultNode->field_vehicle_brand[0]['value']][] = $resultNode->field_vehicle_model[0]['value'];
            } else {
                $brandsAndModels[$resultNode->field_vehicle_brand[0]['value']] = array();
                $brandsAndModels[$resultNode->field_vehicle_brand[0]['value']][] = $resultNode->field_vehicle_model[0]['value'];
            }
        }

        foreach ($brandsAndModels as $key => $value) {
            $brandsAndModels[$key] = array_unique($brandsAndModels[$key]);
        }



        $block['subject'] = 'Vehicle Search Result';
        $block['content'] = '';

        $block['content'] .= '<div id="maintenance-finder">';
        $block['content'] .= '<h2 id="maintenance-finder-header">';

        $block['content'] .= 'TARIFA DE <br/> MANTENIMIENTO <br/>';
        $block['content'] .= '<span>PARA TU VEHICULO</span>';

        $block['content'] .= '</h2>';

        $block['content'] .= '<form method="get" action="/tarifas-de-mantenimiento">';

        $block['content'] .= '<label for="maintenance-finder-brand">MARCA</label>';
        
        $block['content'] .= '<select name="marca" id="maintenance-finder-brand">';
            foreach ($brandsAndModels as $brand => $models) 
            {
                $selected = $brand == 'nissan' ? 'selected="selected"': '';
                $block['content'] .= '<option  value="' . $brand . '"'.$selected.' >';
                $block['content'] .= ucwords($brand);
                $block['content'] .= '</option>';
            }

        $block['content'] .= '</select>';

        $block['content'] .= '<label>';
            $block['content'] .= 'MODELO';
        $block['content'] .= '</label>';
        foreach ($brandsAndModels as $brand => $models) 
        {
            $visible = $brand == 'nissan' ? ' visible' : ' hidden';
            $block['content'] .= '<select class="maintenance-finder-model'.$visible.'" name="modelo" id="maintenance-finder-model-' . $brand . '" >';
            foreach ($models as $model)                 
            {

                $block['content'] .= '<option value="' . $model . '">';
                $block['content'] .= ucwords($model);
                $block['content'] .= '</option>';
            }
            $block['content'] .= '</select>';
        }

        $block['content'] .= '<a id="maintenance-finder-find-button">';
            $block['content'] .= 'BUSCAR';
            
            
        $block['content'] .= '</a>';

        $block['content'] .= '</form>';

        

        

        $block['content'] .= '</div>';
    }

    return $block;
}

