<?php

require_once dirname(__FILE__) . '/../../../../includes/classes/VehicleTypeFilter.php';
require_once dirname(__FILE__) . '/../../../../includes/classes/BrandFilter.php';
require_once dirname(__FILE__) . '/../../../../includes/classes/NullFilter.php';

function maintenance_finder_perm() {
    return array('view_vehicles_search');
}

function maintenance_finder_block($op='list', $delta=0, $edit=array()) {
    require dirname(__FILE__) . '/../../../../includes/paths.php';
    $block = array();
    if ($op == 'list') {
        $block[0]["info"] = t('Front Page Maintenance Finder Block');
        $block[1]["info"] = t('Taller de Servicios Maintenance Finder Block');
    } elseif ($op == 'view') {



        $query = "SELECT * FROM {node} WHERE type = 'vehicle'";
        $results = db_query($query);
        $brandsAndModels = array();
        $rowNodes = array();

        while ($result = db_fetch_object($results)) {

            $resultNode = node_load($result->nid);

            if (isset($brandsAndModels[$resultNode->field_vehicle_brand[0]['value']])) {
                $brandsAndModels[$resultNode->field_vehicle_brand[0]['value']][] = $resultNode->field_vehicle_model[0]['value'];
            } else {
                $brandsAndModels[$resultNode->field_vehicle_brand[0]['value']] = array();
                $brandsAndModels[$resultNode->field_vehicle_brand[0]['value']][] = $resultNode->field_vehicle_model[0]['value'];
            }
        }

        foreach ($brandsAndModels as $key => $value) {
            $brandsAndModels[$key] = array_unique($brandsAndModels[$key]);
        }
        $viewFilePath = '';
       
        $viewFilePath = realpath ('./includes/views/frontPageMaintenanceFinder.php');
       
        
        
        
        
        
        
        
        $block['subject'] = 'Vehicle Search Result';
        $block['content'] = '';

        ob_start();
        require $viewFilePath;
        
        $view = ob_get_contents();        
        ob_end_clean();
        $block['content'] .= $view;
        
        
    }

    return $block;
}

